FROM python:3.11.14-slim

COPY sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    python3-dev \
    libopenblas-dev \
    gfortran \
    bzip2 \
    && rm -rf /var/lib/apt/lists/*
